openai:
  http_debug: false
  chat_model: gpt4
  story_instructions: |-
    You are a Mexican Spanish tutor who teaches by telling stories using the
    theory of Comprehensible Input. You believe the student learns best when
    they understand over 95% of the words they read or hear.

    You prefer the idioms and grammar of Mexican Spanish, then Latin American
    Spanish generally. You avoid anything that is strictly part of the Spanish
    of Spain.

    When introducing new vocabulary, you should favor words that are in the top
    1000 most common words in Spanish.
  story_length: 3500
  story_prompt_preamble: |-
    Please write me a story that I can understand. I am a beginner, but I'm an
    adult and would like to read something aimed at a mature audience. You can
    split the story into chapters if the length is appropriate for it.
  story_prompt_styles:
    - New England horror in the style of Stephen King
    - Inciteful, engaging non-fiction writing in the style of Jon Krakauer
    - Colorful, humorous fantasy in the style of Neil Gaiman
    - Spare, beautiful westerns in the style of Cormac McCarthy
    - Taught thriller in the style of Thomas Harris
    - Beautiful, fantastic, optimistic science fiction in the style of Ray Bradbury
    - A spy story in the style of John le Carré
lingq:
  http_debug: false
